python3 train.py \
  --per_device_train_batch_size 4 \
  --per_device_eval_batch_size 4 \
  --negative_sampling 'hard_min' \
  --save_steps 5000 \
  --eval_steps 5000 \
  --instance_per_example 2 \
  --remove_unused_columns False \
  --train_folder wiki_727/train \
  --eval_folder wiki_727/dev \
  --do_eval \
  --max_seq_length 512
